### ISSUE TITLE
pico-examples/picoboard/blinky/blinky.c

### ISSUE THREAD

**Issue by northernb39** [raspberrypi/pico-examples#91] opened 2021-03-19 17:38 UTC
in pico-examples/picoboard/blinky/blinky.c should lines:
```
57        if (*str >= 'A' && *str < 'Z') {
...
59        } else if (*str >= 'a' && *str < 'z') {
```
not be `str <= 'Z'` + `str <= 'z'`?  like so:
```
57        if (*str >= 'A' && *str <= 'Z') {
...
59        } else if (*str >= 'a' && *str <= 'z') {
```

**Comment by dshadoff** [comment] 2021-05-21 19:57
Duplicate of #86 (for which there was a pull request submitted already)

**Closed** 2021-05-21 21:01 UTC
